### ISSUE TITLE
[UPDATE] 

### ISSUE THREAD

**Issue by sovtec** [crashdemons/DisplayItem-Spigot#24]
[21:07:18 WARN]: [DisplayItem] Task #38547 for DisplayItem v2.9.10-SNAPSHOT-20220618005929User generated an exception
com.github.crashdemons.displayitem_spigot.compatibility.CompatibilityUnavailableException: This server version is not supported and the 'save' method mapping is unknown.
        at com.github.crashdemons.displayitem_spigot.libraries.sainttx.ItemConverter.convertItemStackToJson(ItemConverter.java:97) ~[DisplayItem-Spigot-2.9.10-SNAPSHOT.jar:?]
        at com.github.crashdemons.displayitem_spigot.libraries.sainttx.HoverComponentManager.getTooltipComponent(HoverComponentManager.java:51) ~[DisplayItem-Spigot-2.9.10-SNAPSHOT.jar:?]
        at com.github.crashdemons.displayitem_spigot.libraries.sainttx.HoverComponentManager.getTooltipComponent(HoverComponentManager.java:47) ~[DisplayItem-Spigot-2.9.10-SNAPSHOT.jar:?]
        at com.github.crashdemons.displayitem_spigot.chat.MessageFormatter.formatItemComponents(MessageFormatter.java:47) ~[DisplayItem-Spigot-2.9.10-SNAPSHOT.jar:?]
        at com.github.crashdemons.displayitem_spigot.chat.MessageFormatter.messageInsertItem(MessageFormatter.java:71) ~[DisplayItem-Spigot-2.9.10-SNAPSHOT.jar:?]
        at com.github.crashdemons.displayitem_spigot.chat.ChatLineFormatter.chatLineInsertItem(ChatLineFormatter.java:49) ~[DisplayItem-Spigot-2.9.10-SNAPSHOT.jar:?]
        at com.github.crashdemons.displayitem_spigot.chat.ChatEventExecutor.replaceItem(ChatEventExecutor.java:82) ~[DisplayItem-Spigot-2.9.10-SNAPSHOT.jar:?]
        at com.github.crashdemons.displayitem_spigot.chat.ChatEventExecutor.onChatInternal(ChatEventExecutor.java:117) ~[DisplayItem-Spigot-2.9.10-SNAPSHOT.jar:?]
        at com.github.crashdemons.displayitem_spigot.chat.ChatListener.forceEvent(ChatListener.java:53) ~[DisplayItem-Spigot-2.9.10-SNAPSHOT.jar:?]
        at com.github.crashdemons.displayitem_spigot.DisplayItem.lambda$shareItem$0(DisplayItem.java:74) ~[DisplayItem-Spigot-2.9.10-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.1.jar:git-Paper-102]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480) ~[paper-1.20.1.jar:git-Paper-102]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1480) ~[paper-1.20.1.jar:git-Paper-102]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.20.1.jar:git-Paper-102]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1394) ~[paper-1.20.1.jar:git-Paper-102]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1171) ~[paper-1.20.1.jar:git-Paper-102]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-102]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

```
Paper version git-Paper-102 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 13c9d3c)

DisplayItem version 2.9.10-SNAPSHOT-20220618005929User

**Comment by sovtec** [comment]
Fixed with latest devbuild `https://ci.meme.tips/job/DisplayItem-Spigot/53/`
